### ISSUE TITLE
client: error parsing JSON: unexpected end of JSON input / Errored when setting headers for the spotifyAPI

### ISSUE THREAD

**Issue by tim1f1** [FrostBreker/spotify-private-api#1]
This was working fine until yesterday, now when I try running it, it keeps doing this error message

> 2024/07/16 08:47:03 [INFO] --> Fetching track: 245872G9UaVF63NXm1smrH
> client: error parsing JSON: unexpected end of JSON input
> client: error parsing JSON: unexpected end of JSON input
> 2024/07/16 08:47:03 [ERROR] --> Errored when setting headers for the spotifyAPI
> 2024/07/16 08:47:03 Error fetching track information for track 245872G9UaVF63NXm1smrH: client: error parsing JSON: unexpected end of JSON input
> 2024/07/16 08:47:03 [INFO] --> Fetching track: 5rHzVPOZJQXBieRrCdEea7
> client: error parsing JSON: unexpected end of JSON input
> client: error parsing JSON: unexpected end of JSON input
> 2024/07/16 08:47:03 [ERROR] --> Errored when setting headers for the spotifyAPI
> 2024/07/16 08:47:03 Error fetching track information for track 5rHzVPOZJQXBieRrCdEea7: client: error parsing JSON: unexpected end of JSON input
> 2024/07/16 08:47:03 [INFO] --> Fetching track: 4TfeATq0i5WjsFcNb65UxY
> client: error parsing JSON: unexpected end of JSON input
> client: error parsing JSON: unexpected end of JSON input
> 2024/07/16 08:47:03 [ERROR] --> Errored when setting headers for the spotifyAPI
> 2024/07/16 08:47:03 Error fetching track information for track 4TfeATq0i5WjsFcNb65UxY: client: error parsing JSON: unexpected end of JSON input
> 2024/07/16 08:47:03 [INFO] --> Fetching track: 3c0JVUpU76eOXWkNjT7ymF
> client: error parsing JSON: unexpected end of JSON input
> client: error parsing JSON: unexpected end of JSON input
> 2024/07/16 08:47:03 [ERROR] --> Errored when setting headers for the spotifyAPI
> 2024/07/16 08:47:03 Error fetching track information for track 3c0JVUpU76eOXWkNjT7ymF: client: error parsing JSON: unexpected end of JSON input
> 2024/07/16 08:47:03 [INFO] --> Fetching track: 0bsq4DccyQcwpVEc3CoKfa
> client: error parsing JSON: unexpected end of JSON input
> client: error parsing JSON: unexpected end of JSON input
> 2024/07/16 08:47:03 [ERROR] --> Errored when setting headers for the spotifyAPI
> 2024/07/16 08:47:03 Error fetching track information for track 0bsq4DccyQcwpVEc3CoKfa: client: error parsing JSON: unexpected end of JSON input
> 

I think it might be to do with the late update in the play count yesterday/them updating the API?

**Comment by FrostBreker** [comment]
Hello, I've run some test, can you check if you are using the last version of the package and if your fetching an Id that exist. Try to delete the file response.json.

**Comment by tim1f1** [comment]
> Hello, I've run some test, can you check if you are using the last version of the package and if your fetching an Id that exist. Try to delete the file response.json.

Hi, I did what you suggested, the code seems to be working as normal now, thanks.
